#pragma once

#define TRANSFER_FABRIC_VERSION_MAJOR 1
#define TRANSFER_FABRIC_VERSION_MINOR 0
#define TRANSFER_FABRIC_VERSION_PATCH 0
#define TRANSFER_FABRIC_VERSION "1.0.0"

#define TRANSFER_FABRIC_NAMESPACE transfer_fabric
